Repository mtvs-3rd-outsider/master-of-prediction, pull requests merged in 2024-07, with the labels that each got.

#18 category 및 mybatis, lombok 추가
  build.gradle
  src/main/java/com/outsider/masterofprediction/controller/AdminCategoryController.java
  src/main/java/com/outsider/masterofprediction/dto/TblCategoryDTO.java
  src/main/java/com/outsider/masterofprediction/dto/constatnt/AdminPaginationConstant.java
  src/main/java/com/outsider/masterofprediction/mapper/CategoryMapper.java
  src/main/java/com/outsider/masterofprediction/provider/DeleteByIdsProvider.java
  src/main/java/com/outsider/masterofprediction/service/CategoryService.java
  src/main/java/com/outsider/masterofprediction/utils/PaginationUtils.java
  src/main/resources/templates/content/admin-page/category/index.html
Labels: ✅Feat

#22 19 change folder structure
  src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
  src/main/java/com/outsider/masterofprediction/controller/InquiryController.java
  src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
  src/main/java/com/outsider/masterofprediction/controller/MyPageController.java
  src/main/java/com/outsider/masterofprediction/controller/RankPageController.java
Labels: ✅Feat

#26 이미지 Mapper, DTO 추가
  src/main/java/com/outsider/masterofprediction/dto/TblAttachmentDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/AttachmentMapper.java
Labels: ✅Feat

#24 23 feat user mappe
  src/main/java/com/outsider/masterofprediction/MasterOfPredictionApplication.java
  src/main/java/com/outsider/masterofprediction/dto/TblUserDTO.java
  src/main/java/com/outsider/masterofprediction/dto/User.java
  src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
Labels: ✅Feat

#29 feat: 파일 저장, 제거 서비스 추가
  src/main/java/com/outsider/masterofprediction/service/FileStorageService.java
  src/main/java/com/outsider/masterofprediction/service/ProcessFileService.java
  src/main/java/com/outsider/masterofprediction/utils/FileUtil.java
  src/main/java/com/outsider/masterofprediction/utils/PreviousFileUtils.java
  src/main/java/com/outsider/masterofprediction/utils/ProcessFileInterface.java
Labels: ✅Feat

#34 admin page betting register
  src/main/java/com/outsider/masterofprediction/controller/AdminBettingCreateController.java
  src/main/java/com/outsider/masterofprediction/dto/TblSubjectDTO.java
  src/main/java/com/outsider/masterofprediction/dto/constatnt/SubjectStatus.java
  src/main/java/com/outsider/masterofprediction/dto/response/BettingAndAttachmentDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/SubjectMapper.java
  src/main/java/com/outsider/masterofprediction/service/BettingCreateService.java
  src/main/resources/templates/content/admin-page/betting/create.html
Labels: ✅Feat

#48 40 noti select
  src/main/java/com/outsider/masterofprediction/controller/AdminNoticeController.java
  src/main/java/com/outsider/masterofprediction/dto/Notice.java
  src/main/java/com/outsider/masterofprediction/dto/TblNoticeDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/NoticeMapper.java
  src/main/java/com/outsider/masterofprediction/service/NoticeService.java
  src/main/resources/templates/content/admin-page/notification/index.html
Labels: ✅Feat

#50 feat: 공지사항 등록ui 및 기능 추가
  src/main/java/com/outsider/masterofprediction/controller/AdminNoticeCreateController.java
  src/main/java/com/outsider/masterofprediction/controller/AdminNoticeRedirectCreateFormController.java
  src/main/java/com/outsider/masterofprediction/service/NoticeCreateService.java
  src/main/resources/templates/content/admin-page/notification/create.html
Labels: ✅Feat

#51 feat: 공지사항 삭제
  src/main/java/com/outsider/masterofprediction/controller/AdminNoticeDeleteByIdController.java
  src/main/java/com/outsider/masterofprediction/service/NoticeDeleteByIdService.java
Labels: ✅Feat

#54 feat: 티어 추가
  src/main/java/com/outsider/masterofprediction/controller/TierController.java
  src/main/java/com/outsider/masterofprediction/dto/TblTierDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/TierMapper.java
  src/main/java/com/outsider/masterofprediction/service/TierService.java
Labels: ✅Feat

#57 feat: 문의내역 ui 및 조회기능
  src/main/java/com/outsider/masterofprediction/controller/AdminInquiryController.java
  src/main/java/com/outsider/masterofprediction/dto/CustomTblInquiryDTO.java
  src/main/java/com/outsider/masterofprediction/dto/TblInquiryDTO.java
  src/main/resources/templates/content/admin-page/inquiry/index.html
Labels: ✅Feat

#58 feat: 문의답변 ui 및 답변 저장
  src/main/java/com/outsider/masterofprediction/controller/AdminInquiryReplyController.java
  src/main/java/com/outsider/masterofprediction/controller/AdminInquiryResponseController.java
  src/main/java/com/outsider/masterofprediction/dto/TblInquiryReplyDTO.java
  src/main/java/com/outsider/masterofprediction/dto/constatnt/InquiryReplyStatus.java
  src/main/java/com/outsider/masterofprediction/mapper/InquiryMapper.java
  src/main/java/com/outsider/masterofprediction/mapper/InquiryReplyMapper.java
  src/main/java/com/outsider/masterofprediction/service/InquiryAndReplyResit.java
  src/main/java/com/outsider/masterofprediction/service/InquiryReadService.java
  src/main/java/com/outsider/masterofprediction/service/InquiryReplyCreateService.java
  src/main/java/com/outsider/masterofprediction/service/InquiryStatusUpdateService.java
  src/main/resources/templates/content/admin-page/inquiry/response.html
Labels: ✅Feat

#59 feat: 관리자 기본 페이지 초안
  src/main/java/com/outsider/masterofprediction/controller/AdminHomeController.java
  src/main/resources/templates/content/admin-page/index.html
  src/main/resources/templates/content/admin-page/tier/index.html
Labels: ✅Feat

#61 feat: 관리자 로그인 페이지 초안
  src/main/java/com/outsider/masterofprediction/config/SecurityConfig.java
  src/main/java/com/outsider/masterofprediction/controller/AdminLoginController.java
  src/main/resources/templates/content/admin-page/betting/result.html
  src/main/resources/templates/content/admin-page/login/index.html
Labels: ✅Feat

#82 62 feat root domain design
  src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
  src/main/resources/static/css/header/styles.css
  src/main/resources/static/css/main-page/mainpage.css
  src/main/resources/static/scss/my-page/header.scss
  src/main/resources/templates/content/admin-page/betting/result.html
  src/main/resources/templates/content/main-page/main-page.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/mobileHeader.html
  src/main/resources/templates/layout/main-page/index.html
Labels: Design

#92 62 feat root domain design
  src/main/resources/static/css/main-page/mainpage.css
  src/main/resources/templates/content/main-page/main-page.html
  src/main/resources/templates/fragments/activity.html
  src/main/resources/templates/fragments/rank.html
  src/main/resources/templates/layout/main-page/index.html
Labels: Design

#94 62 feat root domain design
  src/main/resources/templates/content/main-page/main-page.html
Labels: Design

#96 5 betting add page UI
  src/main/java/com/outsider/masterofprediction/controller/BettingAddPageController.java
  src/main/java/com/outsider/masterofprediction/dto/BettingAddDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/BettingAddMapper.java
  src/main/java/com/outsider/masterofprediction/service/BettingAddService.java
  src/main/resources/static/css/betting-add-page/betting-add-page.css
  src/main/resources/templates/fragments/betting-add.html
  src/main/resources/templates/layout/betting-page/add.html
Labels: Design

#109 97 feat admin betting page
  images/logo2.png
  src/main/java/com/outsider/masterofprediction/controller/AdminBettingCreateController.java
  src/main/java/com/outsider/masterofprediction/controller/AdminBettingDeleteController.java
  src/main/java/com/outsider/masterofprediction/controller/AdminBettingUpdateController.java
  src/main/java/com/outsider/masterofprediction/controller/GlobalExceptionHandler.java
  src/main/java/com/outsider/masterofprediction/dto/BettingDeleteOrderDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/BettingDeleteMapper.java
  src/main/java/com/outsider/masterofprediction/service/BettingCreateService.java
  src/main/java/com/outsider/masterofprediction/service/BettingDeleteService.java
  src/main/java/com/outsider/masterofprediction/service/BettingUpdateService.java
  src/main/java/com/outsider/masterofprediction/utils/Validation.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/static/images/400error.png
  src/main/resources/templates/content/admin-page/betting/create.html
  src/main/resources/templates/content/admin-page/betting/create_trash.html
  src/main/resources/templates/content/admin-page/betting/update.html
  src/main/resources/templates/content/admin-page/betting/update_trash.html
  src/main/resources/templates/error/400.html
Labels: ✅Feat

#117 63 랭킹페이지 조회
  package-lock.json
  src/main/java/com/outsider/masterofprediction/MasterOfPredictionApplication.java
  src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
  src/main/java/com/outsider/masterofprediction/controller/RankPageController.java
  src/main/java/com/outsider/masterofprediction/dto/TblAttachmentDTO.java
  src/main/java/com/outsider/masterofprediction/dto/TblUserDTO.java
  src/main/java/com/outsider/masterofprediction/dto/UserAttachmentDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/AttachmentMapper.java
  src/main/java/com/outsider/masterofprediction/mapper/BettingOrderMapper.java
  src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
  src/main/java/com/outsider/masterofprediction/service/ActivityFindService.java
  src/main/java/com/outsider/masterofprediction/service/RankFindService.java
  src/main/resources/main/mappers/BettingOrderMapper.xml
  src/main/resources/main/mappers/UserMapper2.xml
  src/main/resources/mapper/AttachmentMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/content/rank-page/rank-page.html
  src/main/resources/templates/layout/rank-page/index.html
Labels: ✅Feat

#127 feat: 각 작업사항 동기화
  images/logo2.png
  src/main/java/com/outsider/masterofprediction/config/DevSecurityConfig.java
  src/main/java/com/outsider/masterofprediction/controller/BettingController.java
  src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
  src/main/java/com/outsider/masterofprediction/dto/constatnt/StringConstants.java
  src/main/resources/application-autoLogin.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/static/css/admin-page/index.css
  src/main/resources/static/css/betting-page/batting-body.css
  src/main/resources/static/css/betting-page/batting-modal.css
  src/main/resources/static/images/logo2.png
  src/main/resources/static/js/betting-page/betting-page-js.js
  src/main/resources/templates/content/admin-page/fragments/sidebar.html
  src/main/resources/templates/content/betting-page/betting-page.html
  src/main/resources/templates/content/main-page/main-page.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/mypage-desktop-header.html
  src/main/resources/templates/fragments/mypage-header.html
Labels: ✅Feat

#133 121-activitypage-find
  src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
  src/main/java/com/outsider/masterofprediction/dto/ActivityUserSubjectDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/BettingOrderMapper.java
  src/main/java/com/outsider/masterofprediction/service/ActivityFindService.java
  src/main/resources/mapper/BettingOrderMapper.xml
  src/main/resources/templates/content/activity-page/activity-page.html
Labels: ✅Feat

#139 관리자페이지에서 티어 생성 및 수정
  outsider.damx
  src/main/java/com/outsider/masterofprediction/controller/TierController.java
  src/main/java/com/outsider/masterofprediction/dto/TblAttachmentDTO.java
  src/main/java/com/outsider/masterofprediction/dto/TblTierDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/AttachmentMapper.java
  src/main/java/com/outsider/masterofprediction/mapper/TierMapper.java
  src/main/java/com/outsider/masterofprediction/service/TierService.java
  src/main/resources/templates/content/admin-page/tier/create.html
  src/main/resources/templates/content/admin-page/tier/index.html
  src/main/resources/templates/content/admin-page/tier/update.html
Labels: ✅Feat

#143 feat: 더미 데이터 넣기 (#142)
  .gitignore
  docker-compose.yml
  outsider.damx
  src/main/java/com/outsider/masterofprediction/config/SecurityConfigAutoLogin.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/select.sql
Labels: ✅Feat

#152 feat: 메인페이지 활동내역
  src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
  src/main/java/com/outsider/masterofprediction/dto/constatnt/IntConstants.java
  src/main/java/com/outsider/masterofprediction/mapper/BettingOrderMapper.java
  src/main/resources/mapper/BettingOrderMapper.xml
  src/main/resources/templates/fragments/activity.html
Labels: ✅Feat

#153 135-category-based-search
  src/main/java/com/outsider/masterofprediction/controller/CategoryController.java
  src/main/java/com/outsider/masterofprediction/dto/CategoryPageSubjectDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/CategoryPageSubjectMapper.java
  src/main/java/com/outsider/masterofprediction/service/CategoryPageService.java
  src/main/resources/application.properties
  src/main/resources/mapper/CategoryPageSubjectMapper.xml
  src/main/resources/templates/content/category/category.html
Labels: ✅Feat

#154 148-main-page-view-all
  src/main/resources/templates/content/main-page/main-page.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/layout/category/index.html
Labels: ✅Feat

#157 156-header-modification
  src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
  src/main/java/com/outsider/masterofprediction/controller/RankPageController.java
  src/main/resources/templates/fragments/header.html
Labels: Fix

#158 feat: 공지사항페이지 기능 및 ui 수정
  images/upload/Donald.jpg
  src/main/java/com/outsider/masterofprediction/controller/UserNoticeController.java
  src/main/java/com/outsider/masterofprediction/mapper/UserNoticeMapper.java
  src/main/java/com/outsider/masterofprediction/service/UserNoticeService.java
  src/main/resources/data.sql
  src/main/resources/static/css/main-page/mainpage.css
  src/main/resources/static/css/notice-page/notice.css
  src/main/resources/templates/content/notice-page/detail.html
  src/main/resources/templates/content/notice-page/index.html
  src/main/resources/templates/content/notice-page/no-data.html
  src/main/resources/templates/layout/main-page/index.html
Labels: ✅Feat

#166 사진 데이터 및 페이지 생성
  src/main/resources/data.sql
  src/main/resources/static/css/tier/tier.css
  src/main/resources/static/images/tier/apprentice.jpeg
  src/main/resources/static/images/tier/nostradamus.jpeg
  src/main/resources/static/images/tier/novice.jpeg
  src/main/resources/static/images/tier/oracle.jpeg
  src/main/resources/static/images/tier/prophet.jpeg
  src/main/resources/static/images/tier/seer.jpeg
  src/main/resources/templates/content/tier/tier.html
Labels: ✅Feat

#167 메인페이지 Top10랭킹 DB연동
  src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
  src/main/java/com/outsider/masterofprediction/dto/constatnt/IntConstants.java
  src/main/java/com/outsider/masterofprediction/dto/response/UserAndAttachmentDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
  src/main/resources/application.properties
  src/main/resources/static/css/main-page/mainpage.css
  src/main/resources/templates/fragments/rank.html
Labels: ✅Feat

#169 fix: 헤더 css의 경로를 상대경로 -> 절대경로로 변경하였습니다
  src/main/resources/templates/content/login-page/register.html
  src/main/resources/templates/fragments/header.html
Labels: Fix, Design

#177 배팅결과 서비스 추가
  src/main/java/com/outsider/masterofprediction/controller/AdminBettingResultController.java
  src/main/java/com/outsider/masterofprediction/dto/constatnt/StringConstants.java
  src/main/java/com/outsider/masterofprediction/mapper/SubjectMapper.java
  src/main/java/com/outsider/masterofprediction/service/BettingResultService.java
  src/main/java/com/outsider/masterofprediction/service/SubjectService.java
  src/main/java/com/outsider/masterofprediction/service/UserManagementService.java
  src/main/resources/static/css/admin-page/betting/index.css
  src/main/resources/static/css/admin-page/index.css
  src/main/resources/templates/content/admin-page/betting/index.html
  src/main/resources/templates/content/admin-page/betting/result.html
  src/main/resources/templates/content/admin-page/betting/update.html
Labels: ✅Feat

#180 fix: subject status scheduling update
  src/main/java/com/outsider/masterofprediction/service/SubjectService.java
Labels: Fix

#182 feat: tier controller add, tier css update
  src/main/java/com/outsider/masterofprediction/controller/TierViewController.java
  src/main/resources/static/css/tier/tier.css
  src/main/resources/templates/content/tier/tier.html
Labels: ✅Feat, Design

#178 정산하기 버튼 ui 구현
  src/main/java/com/outsider/masterofprediction/controller/BettingController.java
  src/main/java/com/outsider/masterofprediction/dto/RankingDTO.java
  src/main/java/com/outsider/masterofprediction/mapper/SubjectMapper.java
  src/main/resources/application.properties
  src/main/resources/mapper/BettingOrderMapper.xml
  src/main/resources/mapper/SubjectMapper.xml
  src/main/resources/static/css/betting-page/batting-body.css
  src/main/resources/templates/content/betting-page/betting-page.html
Labels: ✅Feat, Design

#188 186-betting-regist-button-bug-fix
  src/main/resources/templates/layout/category/index.html
Labels: Fix

#190 189 feat global user data
  src/main/java/com/outsider/masterofprediction/controller/UserGlobalControllerAdvice.java
  src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
  src/main/resources/templates/fragments/login-header-profile.html
Labels: ✅Feat

#196 메인페이지 상품의 조건을 변경했습니다
  src/main/java/com/outsider/masterofprediction/mapper/MainPageSubjectMapper.java
  src/main/java/com/outsider/masterofprediction/service/SubjectService.java
Labels: Fix

#216 fix: 메인, 활동내역, 랭킹 이미지 버그 수정
  src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
  src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
  src/main/java/com/outsider/masterofprediction/controller/RankPageController.java
  src/main/java/com/outsider/masterofprediction/dto/ActivityUserSubjectDTO.java
  src/main/java/com/outsider/masterofprediction/utils/ConvertImageUrl.java
  src/main/resources/mapper/BettingOrderMapper.xml
  src/main/resources/templates/content/activity-page.html
  src/main/resources/templates/content/rank-page.html
Labels: Fix

#226 225-header-search-bar-modification
  src/main/java/com/outsider/masterofprediction/controller/SearchPageController.java
  src/main/resources/templates/content/search.html
  src/main/resources/templates/fragments/header.html
Labels: ✅Feat, Design

#230 229-image-loading-bug-fix
  src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
  src/main/java/com/outsider/masterofprediction/controller/RankPageController.java
  src/main/java/com/outsider/masterofprediction/dto/ActivityUserSubjectDTO.java
  src/main/java/com/outsider/masterofprediction/dto/UserAttachmentDTO.java
  src/main/resources/application.properties
  src/main/resources/templates/content/rank-page.html
Labels: Fix

#237 feat: 정산하기 모달 구현 & 클릭 시 결과값 서버 전송
  src/main/java/com/outsider/masterofprediction/controller/BettingController.java
  src/main/resources/static/css/betting-page/batting-modal.css
  src/main/resources/static/js/betting-page/betting-page-js.js
  src/main/resources/templates/content/betting-page/betting-page.html
Labels: ✅Feat, Design

#238 feat: 정산하기 버튼 구현2
  src/main/resources/templates/content/betting-page.html
Labels: ✅Feat

#239 feat: 정산하기 모달 구현3
  src/main/resources/static/css/betting-page/batting-modal.css
  src/main/resources/static/js/betting-page/betting-page-js.js
Labels: ✅Feat

#240 feat: 정산하기 모달 구현4
  src/main/resources/static/css/betting-page/batting-modal.css
  src/main/resources/static/js/betting-page/betting-page-js.js
Labels: ✅Feat

#241 feat: 정산하기 모달 구현하기5
  src/main/java/com/outsider/masterofprediction/controller/BettingController.java
  src/main/resources/static/css/betting-page/batting-modal.css
  src/main/resources/static/js/betting-page/betting-page-js.js
Labels: ✅Feat

#242 feat: 정산하기 모달 구현6
  src/main/java/com/outsider/masterofprediction/controller/BettingController.java
  src/main/resources/static/js/betting-page/betting-page-js.js
Labels: ✅Feat

#244 feat: application.properties 경로 수정
  .gitignore
Labels: ✅Feat

#246 245-search-method-modification
  src/main/java/com/outsider/masterofprediction/controller/SearchPageController.java
  src/main/java/com/outsider/masterofprediction/mapper/SearchPageMapper.java
  src/main/java/com/outsider/masterofprediction/service/SearchPageService.java
  src/main/resources/mapper/SearchPageMapper.xml
Labels: ✅Feat

#250 249 feat activity rank css
  .gitignore
  src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
  src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
  src/main/resources/static/css/activity-page/activitypage.css
  src/main/resources/static/css/rank-page/rankpage.css
  src/main/resources/templates/content/activity-page.html
  src/main/resources/templates/content/rank-page.html
  src/main/resources/templates/fragments/activity-content.html
Labels: ✅Feat
